name: golangci-lint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  GOLANGCI_LINT_VERSION: "v1.59.1"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version: '1.21'
          cache: false

      - name: Run vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout 3m --enable=gofmt --verbose
