name: golangci-lint
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup Go
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Run vet
        run: go vet ./...
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v3.7.0
