name: golangci-lint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  GOLANGCI_LINT_VERSION: "v1.58.2"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version: '1.21'
          cache: false

      - name: Run vet
        run: go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --timeout 3m --enable=gofmt --verbose
